# Generated by Django 3.1.1 on 2022-01-03 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokeAgenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=999)),
                ('imagem', models.ImageField(upload_to='images/')),
                ('num_pokemon', models.IntegerField()),
                ('move1', models.CharField(max_length=999)),
                ('move2', models.CharField(max_length=999)),
                ('move3', models.CharField(max_length=999)),
                ('move4', models.CharField(max_length=999)),
            ],
        ),
    ]
